# Based on netbox-community/netbox-docker
services:
  netbox:
    build:
      context: .
      dockerfile: Dockerfile
    image: netbox:latest-plugins
    depends_on:
      - postgres
      - redis
      - redis-cache
    env_file: envs/netbox.env
    user: "unit:root"
    ports:
      - 8000:8080
    volumes:
      - ./configuration/plugins.py:/etc/netbox/config/plugins.py:z,ro
      - ./initializers:/etc/netbox/initializer-data:z,ro

  # postgres
  postgres:
    image: postgres:18-alpine
    env_file: envs/postgres.env
    volumes:
      - netbox-postgres-data:/var/lib/postgresql

  # redis
  redis:
    image: redis:8.6-alpine
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: envs/redis.env
    volumes:
      - netbox-redis-data:/data
  redis-cache:
    image: redis:8.6-alpine
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: envs/redis-cache.env

  prometheus:
    image: prom/prometheus:v3.9.0
    volumes:
      - ./configuration/prometheus.yml:/etc/prometheus/prometheus.yml:ro,z
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    depends_on:
      - netbox

volumes:
  netbox-media-files:
    driver: local
  netbox-postgres-data:
    driver: local
  netbox-redis-data:
    driver: local
